<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
    <Version>0.4.8</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GameValueEditor\GameValueEditor.csproj" />
    <ProjectReference Include="..\..\src\GameValueEditor.ModuleSdk\GameValueEditor.ModuleSdk.csproj" />
  </ItemGroup>

</Project>
