<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>GameValueEditor</AssemblyName>
    <RootNamespace>GameValueEditor</RootNamespace>
    <Product>单机游戏数值编辑器</Product>
    <Description>A local-first memory value editor for offline single-player games.</Description>
    <Version>0.2.0-preview.9</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\GameValueEditorIcon.png" />
  </ItemGroup>

</Project>
